# analysis_options.yaml

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .fvm/**
    - build/**
    - .dart_tool/**

linter:
  rules:
    prefer_single_quotes: true
    directives_ordering: true

    prefer_const_constructors: true
    prefer_const_declarations: true

    avoid_print: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true